### ISSUE TITLE
possibility to use another templating engine?

### ISSUE THREAD

**Issue by oupala** [anatoo/metalsmith-autotoc#3]
It appears that this plugin seems to be linked to **eco** rendering engine.

Could it be possible to use another templating engine such as handlebars?

This could be the opportunity to switch from metalsmith-template to metalsmith-layout.

**Comment by anatoo** [comment]
I used **eco** rendering engine in an example code. But it should be OK to use other template engine.

**Comment by oupala** [comment]
Thanks @anatoo for your answer.

Can you please give an example of the use of autotoc with the handlebars templating engine?

In your example, you're also using the metalsmith-templates module which has been deprecated and replaced by the metalsmith-layout module.

**Comment by ghost** [comment]
I've used it in handlebars.  However, with this example, I can only go 2 level deep.

      <h1>TOC</h1>
       <ul>
         {{#each toc}}
         <li>
           <a href="#{{this.id}}"> {{this.text}} </a>
           {{#if this.children}}
           <ul>
             {{#each this.children}}
             <li>
               <a href="#{{this.id}}"> {{this.text}} </a>
             </li>
             {{/each}}
           </ul>
           {{/if}}
         </li>
         {{/each}}
       </ul>

**Comment by oupala** [comment]
Thanks @up0 and well done.

Since then, I changed my template and I switched to a flat hierarchy where the class is changing the appearance, and not the position in the hierarchy. I now use metalsmith-headings to do that.

Thanks anyway for the tips, it might help anyone!
